export const carsBrandToSvgPath = (brand: string) => {
    return brand.toLowerCase() == 'bmw' ? '/cars-logo/bmw.svg' 
    : brand.toLowerCase() == 'audi' ? '/cars-logo/audi.svg' 
    : brand.toLowerCase() == 'changan' ? '/cars-logo/changan.svg' 
    : brand.toLowerCase() == 'chevrolet' ? '/cars-logo/chevrolet.svg' 
    : brand.toLowerCase() == 'ford' ? '/cars-logo/ford.svg' 
    : brand.toLowerCase() == 'jeep' ? '/cars-logo/jeep.svg' 
    : brand.toLowerCase() == 'geely' ? '/cars-logo/geely.svg' 
    : brand.toLowerCase() == 'lada' ||  brand.toLowerCase() == 'ваз' ? '/cars-logo/lada.svg' 
    : brand.toLowerCase() == 'land-rover' ? '/cars-logo/land-rover.svg' 
    : brand.toLowerCase() == 'lexus' ? '/cars-logo/lexus.svg' 
    : brand.toLowerCase() == 'mazda' ? '/cars-logo/mazda.svg' 
    : brand.toLowerCase() == 'mercedes-benz' ? '/cars-logo/mercedes-benz.svg' 
    : brand.toLowerCase() == 'mitsubishi' ? '/cars-logo/mitsubishi.svg' 
    : brand.toLowerCase() == 'nissan' ? '/cars-logo/nissan.svg' 
    : brand.toLowerCase() == 'peugeot' ? '/cars-logo/peugeot.svg' 
    : brand.toLowerCase() == 'porsche' ? '/cars-logo/porsche.svg' 
    : brand.toLowerCase() == 'renault' ? '/cars-logo/renault.svg' 
    : brand.toLowerCase() == 'skoda' ? '/cars-logo/skoda.svg' 
    : brand.toLowerCase() == 'smart' ? '/cars-logo/smart.svg' 
    : brand.toLowerCase() == 'subaru' ? '/cars-logo/subaru.svg' 
    : brand.toLowerCase() == 'suzuki' ? '/cars-logo/suzuki.svg' 
    : brand.toLowerCase() == 'tesla' ? '/cars-logo/tesla.svg' 
    : brand.toLowerCase() == 'toyota' ? '/cars-logo/toyota.svg' 
    : brand.toLowerCase() == 'volkswagen' ? '/cars-logo/volkswagen.svg' 
    : '/cars-logo/noname.svg'
}